name: package build

on:
  push:
    branches:
    - master
    - branch1 # TODO: remove when branch is done
    - '[0-9]+[\.0-9]*'
    tags:
    - v*
  pull_request:
    branches:
    - master


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: build windows
      shell: powershell
      run: |
        echo doing-something
        echo '::set-env name=UPLOAD_FILE::README.md'
        echo '::set-env name=UPLOAD_ASSET_TYPE::text/plain'
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      #if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: $${{ env.UPLOAD_ASSET_TYPE }}
